[features]
seeds = false
[programs.localnet]
solana_program = "AxhFHpAQtpQag1uZQpjeKxf51YDvt1UgPMiYYcGCKnCR"

[programs.devnet]
solana_program = "AxhFHpAQtpQag1uZQpjeKxf51YDvt1UgPMiYYcGCKnCR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/anamansari/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p ../app/src/idl && cp target/idl/solana_program.json ../app/src/idl/solana_program.json"
